### ISSUE TITLE
Configuration problem

### ISSUE THREAD

**Issue by Mysh3ll** [corus87/kodi-neuron#4]
Hello,

I installed your neuron to pilot kodi by voice.
Kalliope recognizes my orders but my kodi does not react to any orders!

There is my **/brains/kodi.yml** file:

```
- name: "kodi-film"
  signals:
    - order: "liste film"
    - order: "liste films"
    - order: "list film"
    - order: "list films"
  neurons:
    - kodi:
        kodi_ip: "XXX.XXX.XXX.XXX"
        kodi_port: 80
        kodi_login: "login"
        kodi_password: "password"
        show_notifaction: true
        show_video_path: "nfs://XXX.XXX.XXX.XXX/volume1/HDD 2To/Download/Films/"

- name: "kodi-list-film"
  signals:
    - order: "show my library"
  neurons:
    - kodi:
        kodi_ip: "XXX.XXX.XXX.XXX"
        kodi_port: 80
        kodi_login: "login"
        kodi_password: "password"
        show_notifaction: true
        show_video_path: "videodb://movies/titles"
```

Kodi is installed on another raspberry that is on the same network, and my downloads are stored on a NAS which is also on the same network. I can access kodi by opening the browser with the IP address/port/login/password.

Could you help me to configure this neuron? Is there a debug mode to see if I have error messages in return for each voice command?

**Comment by corus87** [comment]
Hi, 
I just realized the read me shows the wrong parameter for the host, port, login and password ! 

The right parameters would be:

```
    - kodi:
        host: "XXX.XXX.XXX.XXX"
        port: 80
        login: "login"
        password: "password"
```
I will fix the read me, thanks for the report!
